export const guides = [
 {slug:'small-business-website-cost',title:'What does a small-business website cost?',description:'Understand what changes a website quote, what to budget for after launch and how to compare proposals.',category:'Budget & scope',service:'business-website-launch',answer:'The useful number is the price for your agreed scope. CodeStudioWorks website projects currently start from $1,250 USD; content, custom features and integrations affect the final quote. Ongoing subscriptions and maintenance should be listed separately.',sections:[
 ['Start with the job the website needs to do','A website that explains three services and collects enquiries is a different project from a shop with product variations, payments and order management. Write down the main action you want a customer to take. Then list the pages and tools needed to support that action. This gives a developer something concrete to price.'],
 ['What changes the build price?','Content preparation, the number of distinct page layouts, editing tools, existing-data migration and custom integrations all affect the work. A booking link to an existing provider is a smaller scope than building your own scheduling rules. Say which approach you expect before comparing quotes.'],
 ['Separate launch costs from running costs','Ask for a separate list covering the domain, hosting, business email, booking software, payment-provider charges and any maintenance agreement. Clarify who owns each account and who pays the provider. A build price does not tell you the total cost of running the site.'],
 ['Compare the same scope','Check that each proposal names the pages, features, content responsibilities, revision rounds, testing, handover and exclusions. Ask what happens if you add a new feature halfway through. A useful quote lets you see what you are buying and what would require a separate agreement.'],
 ['An example to bring to the first conversation','“I need a five-page service website. Customers should be able to request a quote, and I want to edit service descriptions myself. I have a logo and photos, but need help organising the wording.” That is enough to begin a useful discussion; it is not a fixed-price package.']
 ],checklist:['List the main customer action.','Confirm content and editing needs.','Ask for ongoing costs separately.','Agree revisions, ownership and handover.']},
 {slug:'website-web-app-or-mobile-app',title:'Do you need a website, a web app or a mobile app?',description:'Choose the smallest useful starting point for your customers, your workflow and your budget.',category:'Choosing what to build',service:'custom-web-apps',answer:'Start with a website when customers mainly need information and a way to contact, book or buy. Consider a web app for repeat tasks, accounts and custom workflows. Consider a mobile app when the way people use their phones is central to the product.',sections:[
 ['Describe the task before choosing the technology','“Customers need to book a visit” is a clearer starting point than “we need an app.” Describe who will use it, how often, what they need to accomplish and what happens afterward. The answer may be an existing tool connected to a website, rather than a new custom product.'],
 ['When a website is enough','A service business may need clear pages, proof of work, an enquiry form and a booking link. A website can support those journeys without asking visitors to install anything. Content, mobile usability and a straightforward next step matter more than adding features customers will not use.'],
 ['When a web app makes sense','A customer portal, staff dashboard or tailored booking workflow may need accounts, permissions, saved information and business rules. A web app gives those tasks a browser-based interface. Scope the administration side too: someone needs to manage users, correct mistakes and support the process.'],
 ['When to explore a mobile app','A mobile app may suit a product people use repeatedly on their phones, especially when device features or offline behaviour are important. First define those requirements. A mobile release also needs testing, distribution and ongoing updates, so compare the full ownership effort with a browser-based option.'],
 ['Build one complete journey first','For a booking product, a useful first release might let a customer choose a slot, receive confirmation and let staff manage the booking. Add loyalty schemes or complex reporting later if evidence supports them. Keep the first scope small enough to test with real users.']
 ],checklist:['Name the main user and their task.','Estimate how often they will return.','Identify device or offline requirements.','Check whether an existing tool solves the problem.']},
 {slug:'prepare-to-hire-a-freelance-developer',title:'What to prepare before hiring a freelance developer',description:'A practical project brief covering goals, content, access, budget and a clear handover.',category:'Project planning',service:'fractional-development-partner',answer:'Bring a short description of the business, the people you serve, the problem you want to solve and your main constraints. You do not need a technical specification. A clear goal and honest priorities are enough to start planning.',sections:[
 ['Explain the business in plain language','Describe what you sell, who buys it and how customers currently find you. If this is an existing system, explain what works and where people get stuck. For example: “Quote requests arrive in three inboxes and staff copy the details into a spreadsheet.” Specific problems are easier to plan around.'],
 ['Separate essentials from later ideas','Write two lists: what must work at launch and what could wait. Include a target date and explain whether it is tied to an event or simply a preference. Share a budget range so the recommendation can fit your circumstances. The goal is an achievable scope, not a list of every possible feature.'],
 ['Gather useful material','Collect your logo, service descriptions, approved photos, example websites and existing page links. Explain what you like about each example: the navigation, the writing or the booking flow. Check that you have permission to use any supplied images and client statements.'],
 ['Plan access without sharing passwords casually','List the services involved: domain, hosting, email, source code and any payment or booking tools. Keep business accounts under your control. Agree the appropriate way to invite the developer and what access is actually needed; do not put account secrets into a project brief.'],
 ['Agree how the work finishes','Before starting, confirm the scope, price, milestones, feedback process and change requests in writing. Ask what testing, documentation, account access and support are included at handover. An ongoing relationship is useful, but you should understand how your business can operate the finished work.']
 ],checklist:['Business, audience and main problem.','Must-have scope, budget and timing.','Content, examples and existing systems.','Written agreement and handover expectations.']}
];
