import Link from 'next/link';
import {notFound} from 'next/navigation';
import {guides} from '../guides';
import JsonLd from '../../components/JsonLd';
import {absoluteUrl,buildMetadata,breadcrumbSchema,graphSchema} from '../../_lib/seo';
export const dynamicParams=false;
export function generateStaticParams(){return guides.map(g=>({slug:g.slug}));}
export async function generateMetadata({params}){const {slug}=await params;const g=guides.find(g=>g.slug===slug);return g?buildMetadata({title:g.title,description:g.description,path:`/guides/${slug}`}):{};}
export default async function Guide({params}){const {slug}=await params,g=guides.find(g=>g.slug===slug);if(!g)notFound();const path=`/guides/${slug}`;return <main id="main-content" className="architectural-page bg-background pt-[72px]">
<JsonLd data={graphSchema([{'@type':'Article',headline:g.title,description:g.description,mainEntityOfPage:absoluteUrl(path),author:{'@type':'Person',name:'Ryno van Eeden',url:absoluteUrl('/about')},publisher:{'@id':`${absoluteUrl('/')}#organization`}},breadcrumbSchema([{name:'Home',path:'/'},{name:'Guides',path:'/guides'},{name:g.title,path}])])} />
<header className="drafting-process py-16 md:py-24"><div className="section-shell"><Link href="/guides" className="text-accent">← All guides</Link><p className="eyebrow mt-10">{g.category}</p><h1 className="mt-5 max-w-4xl text-4xl md:text-6xl font-black text-secondary">{g.title}</h1><p className="mt-6 text-white/65">By <Link className="underline" href="/about">Ryno van Eeden</Link> · CodeStudioWorks</p></div></header>
<div className="section-shell grid gap-12 py-16 lg:grid-cols-[230px_1fr]"><aside><nav aria-label="In this guide" className="lg:sticky lg:top-28"><p className="eyebrow">In this guide</p>{g.sections.map(([title],i)=><a key={title} href={`#section-${i}`} className="block border-b border-white/15 py-4 text-sm text-white/75 hover:text-accent">{title}</a>)}<Link href="/contact" className="mt-6 inline-block text-accent">Discuss your project ↗</Link></nav></aside><article className="guide-body"><div className="launch-outcome p-7"><h2>The short answer</h2><p>{g.answer}</p></div>{g.sections.map(([title,text],i)=><section id={`section-${i}`} key={title} className="scroll-mt-28 mt-12"><h2>{title}</h2><p>{text}</p></section>)}<section className="drafting-card mt-12"><h2>Your planning checklist</h2><ul>{g.checklist.map(t=><li key={t}>{t}</li>)}</ul></section><div className="mt-12"><h2>Put the plan into practice</h2><p>Tell me about your business and the next step you have in mind. We can work out an appropriate scope together.</p><Link className="studio-primary mt-6" href={`/services/${g.service}`}>Explore the relevant service ↗</Link></div><nav aria-label="Related guides" className="mt-12 border-t border-white/20 pt-8"><h2>Keep planning</h2>{guides.filter(x=>x.slug!==slug).map(x=><Link className="block py-3 text-accent underline" key={x.slug} href={`/guides/${x.slug}`}>{x.title}</Link>)}</nav></article></div></main>}
