import { Caveat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
import Logo from "./components/Logo";
import { Toaster } from "react-hot-toast";
import CopyrightBar from "./components/Copyright-bar";

const caveat = Caveat({
    variable: "--font-caveat",
    subsets: ["latin"],
    weight: ["400"],
});

export const metadata = {
    title: "Custom Web Development from CodeStudioWorks, Michigan",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${caveat.variable} antialiased`}>
                <Logo />
                <Navbar />
                {children}
                <Toaster position="top-right" />
                <CopyrightBar />
            </body>
        </html>
    );
}
